services:

  zookeeper-1:
    image: bitnami/zookeeper:${ZOOKEEPER_VERSION}
    container_name: zookeeper-1
    hostname: zookeeper-1
    env_file:
      - .env
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper-1:2888:3888,zookeeper-2:2888:3888,zookeeper-3:2888:3888
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-1:/bitnami/zookeeper
    restart: always
    networks:
      - hadoop-network

  zookeeper-2:
    image: bitnami/zookeeper:${ZOOKEEPER_VERSION}
    container_name: zookeeper-2
    hostname: zookeeper-2
    env_file:
      - .env
    environment:
      - ZOO_SERVER_ID=2
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper-1:2888:3888,zookeeper-2:2888:3888,zookeeper-3:2888:3888
    ports:
      - "2182:2181"
    volumes:
      - zookeeper-2:/bitnami/zookeeper
    restart: always
    networks:
      - hadoop-network

  zookeeper-3:
    image: bitnami/zookeeper:${ZOOKEEPER_VERSION}
    container_name: zookeeper-3
    hostname: zookeeper-3
    env_file:
      - .env
    environment:
      - ZOO_SERVER_ID=3
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVERS=zookeeper-1:2888:3888,zookeeper-2:2888:3888,zookeeper-3:2888:3888
    ports:
      - "2183:2181"
    volumes:
      - zookeeper-3:/bitnami/zookeeper
    restart: always
    networks:
      - hadoop-network

  hdfs-namenode-1:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: hdfs-namenode-1
    hostname: hdfs-namenode-1
    ports:
      - "9870:9870"
    env_file:
      - .env
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - hdfs-namenode-1:/hadoop/dfs/namenode
      - ./hadoop/config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop/config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./hadoop/script/start-namenode.sh:/start-namenode.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hdfs-namenode-1:9870/"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: ["/bin/bash", "-c", "/start-namenode.sh"]
    restart: always
    networks:
      - hadoop-network

  hdfs-namenode-2:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: hdfs-namenode-2
    hostname: hdfs-namenode-2
    ports:
      - "9871:9870"
    env_file:
      - .env
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - hdfs-namenode-2:/hadoop/dfs/namenode
      - ./hadoop/config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop/config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./hadoop/script/start-namenode.sh:/start-namenode.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hdfs-namenode-2:9870/"]
      interval: 30s
      timeout: 5s
      retries: 3
    command: ["/bin/bash", "-c", "/start-namenode.sh"]
    restart: always
    networks:
      - hadoop-network

  journalnode-1:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: journalnode-1
    hostname: journalnode-1
    ports:
      - "8485:8485"
    env_file:
      - .env
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - journalnode-1:/hadoop/dfs/journalnode
      - ./hadoop/script/start-journalnode.sh:/start-journalnode.sh
    command: ["/bin/bash", "-c", "/start-journalnode.sh"]
    restart: always
    networks:
      - hadoop-network

  journalnode-2:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: journalnode-2
    hostname: journalnode-2
    ports:
      - "8486:8485"
    env_file:
      - .env
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - journalnode-2:/hadoop/dfs/journalnode
      - ./hadoop/script/start-journalnode.sh:/start-journalnode.sh
    command: ["/bin/bash", "-c", "/start-journalnode.sh"]
    restart: always
    networks:
      - hadoop-network

  journalnode-3:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: journalnode-3
    hostname: journalnode-3
    ports:
      - "8487:8485"
    env_file:
      - .env
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - journalnode-3:/hadoop/dfs/journalnode
      - ./hadoop/script/start-journalnode.sh:/start-journalnode.sh
    command: ["/bin/bash", "-c", "/start-journalnode.sh"]
    restart: always
    networks:
      - hadoop-network

  hdfs-datanode-1:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: hdfs-datanode
    hostname: hdfs-datanode
    ports:
      - "9864:9864"
      - "9866:9866"
    depends_on:
      hdfs-namenode-1:
        condition: service_healthy
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - hdfs-datanode-1:/hadoop/dfs/datanode
      - ./hadoop/config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop/config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./hadoop/script/start-datanode.sh:/start-datanode.sh
    command: ["/bin/bash", "-c", "/start-datanode.sh"]
    restart: always
    networks:
      - hadoop-network

  hdfs-datanode-2:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: hdfs-datanode-2
    hostname: hdfs-datanode-2
    ports:
      - "9865:9864"
      - "9867:9866"
    depends_on:
      hdfs-namenode-2:
        condition: service_healthy
    environment:
      - HADOOP_HOME=/opt/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - hdfs-datanode-2:/hadoop/dfs/datanode
      - ./hadoop/config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./hadoop/config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./hadoop/script/start-datanode.sh:/start-datanode.sh
    command: ["/bin/bash", "-c", "/start-datanode.sh"]
    restart: always
    networks:
      - hadoop-network

volumes:
  zookeeper-1:
    driver: local
    driver_opts:
      type: none
      device: ./persistence/zookeeper-1
      o: bind

  zookeeper-2:
    driver: local
    driver_opts:
      type: none
      device: ./persistence/zookeeper-2
      o: bind

  zookeeper-3:
    driver: local
    driver_opts:
      type: none
      device: ./persistence/zookeeper-3
      o: bind

  hdfs-namenode-1:
    driver: local
    driver_opts:
      type: none
      device: ./persistence/hdfs-namenode-1/dfs/namenode
      o: bind

  hdfs-namenode-2:
    driver: local
    driver_opts:
      type: none
      device: ./persistence/hdfs-namenode-2/dfs/namenode
      o: bind

  hdfs-datanode-1:
    driver: local
    driver_opts:
      type: none
      device: ./persistence/hdfs-datanode-1/dfs/datanode
      o: bind

  hdfs-datanode-2:
    driver: local
    driver_opts:
      type: none
      device: ./persistence/hdfs-datanode-2/dfs/datanode
      o: bind

  journalnode-1:
    driver: local
    driver_opts:
      type: none
      device: ./persistence/journalnode-1
      o: bind

  journalnode-2:
    driver: local
    driver_opts:
      type: none
      device: ./persistence/journalnode-2
      o: bind

  journalnode-3:
    driver: local
    driver_opts:
      type: none
      device: ./persistence/journalnode-3
      o: bind

networks:
  hadoop-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000
    ipam:
      config:
        - subnet: 172.15.0.0/16